import { test, expect, type APIRequestContext } from "@playwright/test"
import { API, authHeaders, createMember, matchMembers, signedInPage, type Member } from "./helpers"

const backOut = /^(Cancel|Keep|No\b)/

const thread = async (request: APIRequestContext, member: Member, matchId: string) =>
  (await (await request.get(`${API}/messages/${matchId}`, { headers: authHeaders(member.token) })).json()) as any

test.describe("Messages: the remaining controls", () => {
  test("MSG-06/08: no conversations yet - says what to do next", async ({ browser, request }) => {
    const me = await createMember(request)
    const page = await signedInPage(browser, me, "/messages")
    await expect(page.getByText("No conversations yet")).toBeVisible()
    await expect(page.getByText("When you and another member like each other, you can write to them here.")).toBeVisible()
    await expect(page.getByText("Choose a conversation")).toBeVisible()
    await page.getByRole("link", { name: "Browse members" }).click()
    await expect(page).toHaveURL(/\/browse$/)
    await page.context().close()
  })

  test("MSG-02/07: find a conversation by name; no match explains and offers Show everyone", async ({ browser, request }) => {
    const me = await createMember(request)
    const ann = await createMember(request, { firstName: "Annika" })
    const bo = await createMember(request, { firstName: "Bodhi" })
    await matchMembers(request, me, ann)
    await matchMembers(request, me, bo)
    const page = await signedInPage(browser, me, "/messages")
    const items = page.getByTestId("conversation-item")
    await expect(items).toHaveCount(2)
    const find = page.getByPlaceholder("Find by name")
    await find.fill("bod")
    await expect(items).toHaveCount(1)
    await expect(items.first()).toContainText("Bodhi")
    await find.fill("zzz")
    await expect(page.getByText('Nobody called "zzz" in your conversations.')).toBeVisible()
    await page.getByRole("button", { name: "Show everyone" }).click()
    await expect(items).toHaveCount(2)
    await expect(find).toHaveValue("")
    await page.context().close()
  })

  test("MSG-15/18/34/38: backing out of Unmatch, Clear conversation, Edit and Unsend changes nothing", async ({ browser, request }) => {
    const me = await createMember(request)
    const other = await createMember(request, { firstName: "Carmen" })
    const matchId = await matchMembers(request, me, other)
    await request.post(`${API}/messages/${matchId}`, { headers: authHeaders(me.token), data: { content: "My first message" } })
    const page = await signedInPage(browser, me, `/messages?match=${matchId}`)
    const mine = page.getByTestId("message-own").filter({ hasText: "My first message" })
    await expect(mine).toBeVisible()

    await page.getByTestId("chat-options").click()
    await page.getByRole("menuitem", { name: "Unmatch" }).click()
    let dialog = page.getByRole("dialog", { name: "Unmatch with Carmen?" })
    await dialog.getByRole("button", { name: backOut }).click()
    await expect(dialog).toBeHidden()

    await page.getByTestId("chat-options").click()
    await page.getByRole("menuitem", { name: "Clear conversation" }).click()
    dialog = page.getByRole("dialog", { name: "Clear this conversation?" })
    await dialog.getByRole("button", { name: backOut }).click()
    await expect(dialog).toBeHidden()
    await expect(mine).toBeVisible()

    await page.getByRole("button", { name: "Edit", exact: true }).click()
    await page.getByLabel("Change your message").fill("Something else entirely")
    await page.getByRole("button", { name: "Cancel" }).click()
    await expect(mine).toBeVisible()
    await page.getByRole("button", { name: "Edit", exact: true }).click()
    await page.getByLabel("Change your message").fill("Something else again")
    await page.keyboard.press("Escape")
    await expect(mine).toBeVisible()
    await expect(page.getByText("Edited")).toHaveCount(0)

    await page.getByRole("button", { name: "Unsend", exact: true }).click()
    dialog = page.getByRole("dialog", { name: "Unsend this message?" })
    await dialog.getByRole("button", { name: backOut }).click()
    await expect(dialog).toBeHidden()
    await expect(mine).toBeVisible()

    const after = await thread(request, me, matchId)
    expect(JSON.stringify(after)).toContain("My first message")
    const matches = await (await request.get(`${API}/matches`, { headers: authHeaders(me.token) })).json()
    expect(matches.active).toHaveLength(1)
    await page.context().close()
  })

  test("MSG-31: the emoji picker adds to the message and closes; works from the keyboard", async ({ browser, request }) => {
    const me = await createMember(request)
    const other = await createMember(request, { firstName: "Dario" })
    const matchId = await matchMembers(request, me, other)
    const page = await signedInPage(browser, me, `/messages?match=${matchId}`)
    const message = page.getByPlaceholder("Write to Dario")
    await message.fill("Happy birthday ")
    await page.getByRole("button", { name: /Emoji|Add an emoji/ }).click()
    await expect(page.getByText("Smiles")).toBeVisible()
    await expect(page.getByText("Hands and hearts")).toBeVisible()
    await page.getByRole("button", { name: "Add 🎂" }).click()
    await expect(message).toHaveValue("Happy birthday 🎂")
    await expect(page.getByRole("button", { name: "Add 🎂" })).toBeHidden()

    await page.getByRole("button", { name: /Emoji|Add an emoji/ }).focus()
    await page.keyboard.press("Enter")
    await page.getByRole("button", { name: "Add 🎉" }).focus()
    await page.keyboard.press("Enter")
    await expect(message).toHaveValue("Happy birthday 🎂🎉")
    await page.getByRole("button", { name: "Send", exact: true }).click()
    await expect(page.getByTestId("message-own").filter({ hasText: "Happy birthday 🎂🎉" })).toBeVisible()
    await page.context().close()
  })

  test("MSG-10/12/43: on a phone - one pane at a time, Back returns to the list, View profile is in Options", async ({ browser, request }) => {
    const me = await createMember(request)
    const other = await createMember(request, { firstName: "Esme" })
    const matchId = await matchMembers(request, me, other)
    const page = await signedInPage(browser, me, "/messages", { viewport: { width: 390, height: 844 } })
    const item = page.getByTestId("conversation-item").filter({ hasText: "Esme" })
    await item.click()
    await expect(page).toHaveURL(new RegExp(`match=${matchId}`))
    await expect(page.getByPlaceholder("Write to Esme")).toBeVisible()
    await expect(item).toBeHidden()
    await page.getByRole("button", { name: "Back", exact: true }).click()
    await expect(item).toBeVisible()
    await expect(page.getByPlaceholder("Write to Esme")).toBeHidden()

    await item.click()
    await page.getByTestId("chat-options").click()
    await page.getByRole("menuitem", { name: "View profile" }).click()
    await expect(page).toHaveURL(new RegExp(`/profile/${other.id}`))
    await expect(page.getByRole("heading", { name: "Esme", level: 1 })).toBeVisible()
    await page.context().close()
  })

  test("A11Y: new messages, typing and toasts are announced (live regions)", async ({ browser, request }) => {
    const me = await createMember(request, { firstName: "Flo" })
    const other = await createMember(request, { firstName: "Gene" })
    const matchId = await matchMembers(request, me, other)
    const page = await signedInPage(browser, me, `/messages?match=${matchId}`)
    const log = page.getByTestId("message-thread")
    await expect(log).toHaveAttribute("role", "log")
    await expect(log).toHaveAttribute("aria-label", "Messages with Gene")
    // A message from the other member lands in the log and in the polite announcer.
    await request.post(`${API}/messages/${matchId}`, { headers: authHeaders(other.token), data: { content: "Are you coming on Saturday?" } })
    await expect(log.getByText("Are you coming on Saturday?")).toBeVisible()
    await expect(log.getByText("Gene said:", { exact: false }).first()).toBeAttached()
    // (role="log" is itself a polite live region, so the new line is read out.)
    await expect(page.locator('[aria-live="polite"]').first()).toBeAttached()
    // Toasts are rendered inside a live region.
    await page.getByTestId("chat-options").click()
    await page.getByRole("menuitem", { name: "Block Gene" }).click()
    await page.getByRole("dialog").getByRole("button", { name: /^Block/ }).click()
    const toast = page.locator("[data-sonner-toast]").first()
    await expect(toast).toBeVisible()
    expect(await toast.evaluate((el) => Boolean(el.closest('[aria-live], [role="status"], [role="alert"], [role="region"]')))).toBe(true)
    await page.context().close()
  })
})
